### PR TITLE
Fix PV grid connection fee edge case

### LINKED ISSUE #2205: PV monthly grid connection fee can apply even if no PV
When [`MonthlyGridConnectionFee`](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#pv-compensation) is specified using $/kW, it will [correctly be zero](https://github.com/NatLabRockies/OpenStudio-HPXML/blob/66ef3dbf7fb2577fb847841752db187843065854/ReportUtilityBills/measure.rb#L320-L324) but if specified using $, it [does not check for the existence of PV](https://github.com/NatLabRockies/OpenStudio-HPXML/blob/66ef3dbf7fb2577fb847841752db187843065854/ReportUtilityBills/measure.rb#L326-L327).

A bit of an edge case, but it can come up in the context of BEopt where you might be optimizing across designs with and without PV, and you're setting the PV compensation inputs for the entire analysis. Noticed by @jmaguire1.

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Closes #2205.

## Checklist

Not all may apply:

- [ ] Schematron validator (`EPvalidator.sch`) has been updated
- [ ] Sample files have been added/updated (`openstudio tasks.rb update_hpxmls`)
- [x] Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests/test*.rb` and/or `workflow/tests/test*.rb`)
- [ ] Documentation has been updated
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

File: ReportUtilityBills/tests/test_report_utility_bills.rb [hunk 1]
```diff
@@ -501,635 +486,557 @@ def test_downloaded_utility_rates
...
+  end
+
+  def test_pv_none_with_pv_grid_fee_dollars
+    # Check PV grid fee not applied if no PV
+    @hpxml.header.utility_bill_scenarios[-1].pv_monthly_grid_connection_fee_dollars = 7.50
+    @hpxml_bldg.pv_systems.clear
+    actual_bills, actual_monthly_bills = _bill_calcs(@fuels_pv_none_simple, @hpxml)
+    _check_bills(@expected_bills, actual_bills)
+    _check_monthly_bills(actual_bills, actual_monthly_bills)
+  end
```
Comment (shorowit) [inline ReportUtilityBills/tests/test_report_utility_bills.rb:913]: This test fails before the bugfix.

File: ReportUtilityBills/measure.rb [hunk 2]
```diff
@@ -324,7 +324,10 @@ def get_pv_monthly_fee(bill_scenario, hpxml_buildings)
         end
       end
     elsif not bill_scenario.pv_monthly_grid_connection_fee_dollars.nil?
-      pv_monthly_fee = bill_scenario.pv_monthly_grid_connection_fee_dollars
+      has_pv = hpxml_buildings.map { |hpxml_bldg| hpxml_bldg.pv_systems.map { |pv_system| pv_system.max_power_output }.sum }.sum > 0
+      if has_pv
+        pv_monthly_fee = bill_scenario.pv_monthly_grid_connection_fee_dollars
+      end
```
Comment (shorowit) [inline ReportUtilityBills/measure.rb:330]: And this is the bugfix.

Comment (jmaguire1) [reply ReportUtilityBills/measure.rb:330]: Wow that was fast! Thanks @shorowit!

File: ReportUtilityBills/tests/test_report_utility_bills.rb [hunk 3]
```diff
@@ -106,76 +105,63 @@ def teardown
...
 
   def test_simple_pv_1kW_net_metering_user_excess_rate
     @hpxml_bldg.pv_systems.each { |pv_system| pv_system.max_power_output = 1000.0 / @hpxml_bldg.pv_systems.size }
-    utility_bill_scenario = @hpxml_header.utility_bill_scenarios[0]
-    actual_bills, actual_monthly_bills = _bill_calcs(@fuels_pv_1kw_simple, @hpxml_header, @hpxml.buildings, utility_bill_scenario)
+    actual_bills, actual_monthly_bills = _bill_calcs(@fuels_pv_1kw_simple, @hpxml)
     @expected_bills['Test: Electricity: PV Credit (USD)'] = -177
-    expected_bills = _get_expected_bills(@expected_bills)
-    _check_bills(expected_bills, actual_bills)
+    _check_bills(@expected_bills, actual_bills)
```
Comment (shorowit) [inline ReportUtilityBills/tests/test_report_utility_bills.rb:118]: Unrelated cleanup throughout to reduce LOC and simplify `_bill_calcs` method signature.
