### PR TITLE
Fix possible simulation error related to EPW path.

### LINKED ISSUE #1497: Sim error if EPW next to HPXML and relative path used
E.g., put foo.epw next to foo.xml in the same dir, and use "foo.epw" in the HPXML. Gives an error.

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Closes #1497.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [ ] Schematron validator (`EPvalidator.xml`) has been updated
- [ ] Sample files have been added/updated (via `tasks.rb`)
- [ ] Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests` and/or `workflow/tests/hpxml_translator_test.rb`)
- [ ] Documentation has been updated
- [ ] Changelog has been updated
- [ ] `openstudio tasks.rb update_measures` has been run
- [ ] No unexpected changes to simulation results of sample files

### CODE REVIEW

File: HPXMLtoOpenStudio/resources/location.rb [hunk 1]
```diff
@@ -82,24 +82,26 @@ def self.get_climate_zone_iecc(wmo)
   end
 
   def self.get_epw_path(hpxml, hpxml_path)
-    epw_path = hpxml.climate_and_risk_zones.weather_station_epw_filepath
+    epw_filepath = hpxml.climate_and_risk_zones.weather_station_epw_filepath
+    abs_epw_path = File.absolute_path(epw_filepath)
```
Comment (shorowit) [inline HPXMLtoOpenStudio/resources/location.rb:86]: This is the bugfix, the rest is cleanup. If the HPXML file is in your current working directory, then `epw_path` will remain a relative path and get written to the OSM as a relative path. This causes downstream problems since the OSM ends up in a different directory, so the weather file is no longer relative to it. So the bugfix is to make sure we always convert the `epw_path` to an absolute path for the OSM.

Comment (shorowit) [reply HPXMLtoOpenStudio/resources/location.rb:86]: Note that in most situations, the relative path was correctly ended up as an absolute path in the OSM. But in this one particular situation, it wasn't.
