### PR TITLE
Fixes #1060

### LINKED ISSUE #1060: Handle error for non-existent output variable
```
$ /c/openstudio-3.4.0-rc1/bin/openstudio.exe workflow/run_simulation.rb -x workflow/sample_files/base.xml --add-timeseries-output-variable "Made up"
HPXML: C:/OpenStudio/OpenStudio-HPXML/workflow/sample_files/base.xml
Creating input...
Running simulation...
Completed simulation in 3.4s.
Processing output...
Processing output unsuccessful.
See C:/OpenStudio/OpenStudio-HPXML/workflow/sample_files/run/run.log for details.
```

run.log:
```
Error: Measure Failed with Error: undefined method `[]' for nil:NilClass
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:1696:in `get_report_variable_data_timeseries_key_values_and_units'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:828:in `block in get_outputs'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:827:in `each'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:827:in `get_outputs'
C:/OpenStudio/OpenStudio-HPXML/ReportSimulationOutput/measure.rb:487:in `run'
```

Need to throw a more useful error message.

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Fixes #1060. Fixes ReportSimulationOutput error if a user requests a non-existent output variable and no other timeseries outputs. (If they requested other valid timeseries outputs, the error did not occur.) Updates workflow test to check for success.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [x] ~Schematron validator (`EPvalidator.xml`) has been updated~
- [x] ~Sample files have been added/updated (via `tasks.rb`)~
- [x] Unit tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests`)
- [x] ~Documentation has been updated~
- [x] ~Changelog has been updated~
- [x] `openstudio tasks.rb update_measures` has been run
- [x] ~Checked the code coverage report on CI~
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

File: ReportSimulationOutput/measure.rb [hunk 1]
```diff
@@ -227,10 +227,10 @@ def energyPlusOutputRequests(runner, user_arguments)
       include_timeseries_zone_temperatures = include_timeseries_zone_temperatures.is_initialized ? include_timeseries_zone_temperatures.get : false
       include_timeseries_airflows = include_timeseries_airflows.is_initialized ? include_timeseries_airflows.get : false
       include_timeseries_weather = include_timeseries_weather.is_initialized ? include_timeseries_weather.get : false
-      @user_output_variables = @user_output_variables.is_initialized ? @user_output_variables.get : false
+      user_output_variables = user_output_variables.is_initialized ? user_output_variables.get : nil
```
Comment (shorowit) [inline ReportSimulationOutput/measure.rb:230]: No need for a global variable, it can easily be made a local variable and passed to `setup_outputs`. Also, it's not boolean so it shouldn't default to false if not provided.

File: ReportSimulationOutput/measure.rb [hunk 2]
```diff
@@ -1693,11 +1693,13 @@ def get_report_variable_data_timeseries(key_values, variables, unit_conv, unit_a
   def get_report_variable_data_timeseries_key_values_and_units(timeseries_frequency, var)
     keys = []
     units = ''
-    @msgpackDataTimeseries['Cols'].each do |col|
-      next unless col['Variable'].end_with? ":#{var}"
+    if not @msgpackDataTimeseries.nil?
```
Comment (shorowit) [inline ReportSimulationOutput/measure.rb:1696]: Checking for nil is the actual fix. If you request output variables that don't exist, _and request no other timeseries outputs_, then E+ won't even create the timeseries output msgpack file.

File: workflow/tests/hpxml_translator_test.rb [hunk 3]
```diff
@@ -174,26 +174,44 @@ def test_run_simulation_detailed_schedules
...
+        assert_equal(1, timeseries_rows[0].select { |r| r == 'TimeDST' }.size)
+        assert_equal(1, timeseries_rows[0].select { |r| r == 'TimeUTC' }.size)
+        assert_equal(1, timeseries_rows[0].select { |r| r == 'Zone People Occupant Count: Living Space' }.size)
+        assert_equal(1, timeseries_rows[0].select { |r| r == 'Zone People Total Heating Energy: Living Space' }.size)
+      end
+
+      # Check run.log has warning about missing Foobar Variable
+      assert(File.exist? File.join(File.dirname(xml), 'run', 'run.log'))
+      log_lines = File.readlines(File.join(File.dirname(xml), 'run', 'run.log')).map(&:strip)
+      assert(log_lines.include? "Warning: Request for output variable 'Foobar Variable' returned no key values.")
```
Comment (shorowit) [inline workflow/tests/hpxml_translator_test.rb:213]: Updated the test to check for the missing output variable warning (whether requested alongside other timeseries outputs or by itself, the latter of which is fixed by this PR).

File: ReportSimulationOutput/measure.rb (hunk 2 above)
Comment (joseph-robertson) [reply ReportSimulationOutput/measure.rb:1696]: So to be clear, we are ignoring non-existent output variables and not throwing a warning or anything like that?

Comment (shorowit) [reply ReportSimulationOutput/measure.rb:1696]: No, a warning is always issued. Previously it would hit an error before it got to providing a warning.

File: workflow/tests/hpxml_translator_test.rb [hunk 4]
```diff
@@ -174,26 +174,44 @@ def test_run_simulation_detailed_schedules
...
-    assert_equal(1, timeseries_rows[0].select { |r| r == 'TimeDST' }.size)
-    assert_equal(1, timeseries_rows[0].select { |r| r == 'TimeUTC' }.size)
-    assert_equal(1, timeseries_rows[0].select { |r| r == 'Zone People Occupant Count: Living Space' }.size)
-    assert_equal(1, timeseries_rows[0].select { |r| r == 'Zone People Total Heating Energy: Living Space' }.size)
+      # Check for output files
+      assert(File.exist? File.join(File.dirname(xml), 'run', 'eplusout.msgpack'))
+      assert(File.exist? File.join(File.dirname(xml), 'run', 'results_annual.csv'))
+      assert(File.exist? File.join(File.dirname(xml), 'run', 'results_hpxml.csv'))
+      if not invalid_variable_only
+        assert(File.exist? File.join(File.dirname(xml), 'run', 'results_timeseries.csv'))
```
Comment (joseph-robertson) [inline workflow/tests/hpxml_translator_test.rb:197]: Should we assert that `results_timeseries.csv` _doesn't_ exist when `invalid_variable_only=true`?

Comment (shorowit) [reply workflow/tests/hpxml_translator_test.rb:197]: Good idea, I'll do that.
