### PR TITLE
Fix furnace heating airflow bug

### LINKED ISSUE #1739: Furnace heating airflow bug
@shorowit, I believe this [method](https://github.com/NREL/OpenStudio-HPXML/blob/32afb154c8642b77b1b8d0a12673d80c0f4d251b/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L2719) is being applied incorrectly for furnaces. The method currently forces furnace airflow rates to be 300 cfm/ton. Furnace "cfm/ton" should be approximately 218 cfm/ton based on a 120 F supply air temperature.

I think this should be a simple fix. Please tag @joseph-robertson in the PR, so he can include the fix in our ResStock branch.

### PR DESCRIPTION
**Pull request by shorowit**
## Pull Request Description

Closes #1739. Fixes cfm/ton restriction from incorrectly applying to furnace heating airflow rate. And some light refactoring.

## Checklist

PR Author: Check these when they're done. Not all may apply. ~~strikethrough~~ and check any that do not apply. 

PR Reviewer: Verify each has been completed.

- [x] ~Schematron validator (`EPvalidator.xml`) has been updated~
- [x] ~Sample files have been added/updated (`openstudio tasks.rb update_hpxmls`)~
- [x] ~Tests have been added/updated (e.g., `HPXMLtoOpenStudio/tests/test*.rb` and/or `workflow/tests/test*.rb`)~
- [x] ~Documentation has been updated~
- [x] Changelog has been updated
- [x] `openstudio tasks.rb update_measures` has been run
- [x] No unexpected changes to simulation results of sample files

### CODE REVIEW

File: HPXMLtoOpenStudio/resources/hvac_sizing.rb [hunk 1]
```diff
@@ -2078,27 +2080,27 @@ def self.apply_hvac_equipment_adjustments(mj, runner, hvac_sizings, weather, hva
...
-      hvac_sizings.Heat_Airflow = calc_airflow_rate_manual_s(mj, hvac_sizings.Heat_Capacity, (supply_air_temp - mj.heat_setpoint), hvac_sizings.Heat_Capacity)
+      hvac_sizings.Heat_Airflow = calc_airflow_rate_manual_s(mj, hvac_sizings.Heat_Capacity, heating_delta_t, dx_capacity: hvac_sizings.Heat_Capacity)
 
     elsif (heating_type == HPXML::HVACTypeFurnace) || ((not hvac_cooling.nil?) && hvac_cooling.has_integrated_heating)
 
       hvac_sizings.Heat_Capacity = hvac_sizings.Heat_Load
       hvac_sizings.Heat_Capacity_Supp = 0.0
 
-      hvac_sizings.Heat_Airflow = calc_airflow_rate_manual_s(mj, hvac_sizings.Heat_Capacity, (supply_air_temp - mj.heat_setpoint), hvac_sizings.Heat_Capacity)
+      hvac_sizings.Heat_Airflow = calc_airflow_rate_manual_s(mj, hvac_sizings.Heat_Capacity, heating_delta_t)
```
Comment (shorowit) [inline HPXMLtoOpenStudio/resources/hvac_sizing.rb:2103]: This is the bugfix; removed the final argument from being passed to the method.
